[package]
name = "project_peril"
version = "0.2.0"
authors = ["Lars-Ivar Hesselberg Simonsen <larsivarhs@gmail.com>","Matthew Guise <reaverrikku@gmail.com>"]
build = "build.rs"

[build-dependencies]
glob = "0.2.11"

[features]
debug_layer = [] # enables debug layer

[dependencies]
ash = "0.27.1"
cgmath = "0.17.0"
image = "0.21.0"
serde = "1.0.85"
serde_derive = "1.0.85"
serde_json = "1.0.36"
winit = "0.18.1"
