[package]
name = "project_peril"
version = "0.1.0"
authors = ["Lars-Ivar Hesselberg Simonsen <larsivarhs@gmail.com>","Matthew Guise <reaverrikku@gmail.com>"]

[dependencies]
regex = "0.2.2"
vulkano = "0.7.2"
