[package]
name = "project_peril"
version = "0.1.3"
authors = ["Lars-Ivar Hesselberg Simonsen <larsivarhs@gmail.com>","Matthew Guise <reaverrikku@gmail.com>"]
build = "build.rs"

[build-dependencies]
glob = "0.2.11"

[features]
debug_layer = [] # enables debug layer

[dependencies]
ash = "0.20.1"
cgmath = "0.16.0"
image = "0.18.0"
serde = "1.0.32"
serde_derive = "1.0.32"
serde_json = "1.0.11"
winit = "0.8.3"
