# Allman style braces
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

# Tabs instead of spaces
hard_tabs = true

# Don't move operators to the start of next line
binop_separator = "Back"

# Don't differentiate formatting based on size
use_small_heuristics = "Off"

# Function arguments shouldn't take up one line each
fn_args_density = "Compressed"

# Most people have wide screen monitors these days
max_width = 120

# Various comment fixes
normalize_comments = true
wrap_comments = true
comment_width = 120

# Alphabetical order is nice
reorder_imports = true
reorder_modules = true
